### ISSUE TITLE
Crash after world load: "Cannot invoke "appeng.api.storage.data.IAEItemStack.getStackSize()" because "request" is null"

### ISSUE THREAD

**Issue by unilock** [GTNewHorizons/Applied-Energistics-2-Unofficial#551] opened 2024-08-15 16:18 UTC
I was visiting a friend's base when I saw their AE2 system wasn't receiving power due to a wiring misconfiguration. Upon reconnecting it, the server crashed with the following error from AE2:

```
java.lang.NullPointerException: Cannot invoke "appeng.api.storage.data.IAEItemStack.getStackSize()" because "request" is null
```

This error and crash now occur every time the server starts and the world is fully loaded. Downgrading AE2 as far as `rv3-beta-418-GTNH` did not fix the issue.

***

AE2 version: `rv3-beta-427-GTNH-pre`

`crash-2024-08-15_12.08.12-server.txt`: https://gist.github.com/unilock/c5668e64d7a8133295f525e06fbce2e9  
`fml-server-latest.log`: https://gist.github.com/unilock/e18073bb42da1102ea72eb8657b4b81c (exception on line 55667)

**Comment by hiroscho** [comment] 2024-08-15 17:36
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16978 

Caused by PR https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/545 (and already fixed)

Downgrade AE2 and AE2FC or find the fixed jars I posted in Discord

**Comment by unilock** [comment] 2024-08-15 19:02
@hiroscho If this issue is caused by that PR, shouldn't it have been fixed by downgrading AE2 to `rv3-beta-418-GTNH`?

**Closed** 2024-12-31 17:26 UTC
