### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by SrYthan** [GTNewHorizons/Applied-Energistics-2-Unofficial#414] opened 2023-10-25 21:16 UTC
Time: 10/24/23 10:16 PM
Description: Exception getting block type in world

java.lang.NullPointerException: Exception getting block type in world
	at net.minecraft.world.World.func_147439_a(World.java:683)
	at net.minecraft.tileentity.TileEntityChest.func_145977_a(TileEntityChest.java:327)
	at net.minecraft.tileentity.TileEntityChest.func_145979_i(TileEntityChest.java:277)
	at appeng.util.Platform.generateTileHash(Platform.java:1369)
	at appeng.parts.automation.PartSharedItemBus.getHandler(PartSharedItemBus.java:95)
	at appeng.parts.automation.PartImportBus.getTickingRequest(PartImportBus.java:166)
	at appeng.me.cache.TickManagerCache.addNode(TickManagerCache.java:143)
	at appeng.me.GridCacheWrapper.addNode(GridCacheWrapper.java:40)
	at appeng.me.Grid.add(Grid.java:163)
	at appeng.me.GridNode.setGrid(GridNode.java:209)
	at appeng.me.GridPropagator.visitNode(GridPropagator.java:28)
	at appeng.me.GridNode.visitorNode(GridNode.java:459)
	at appeng.me.GridNode.beginVisit(GridNode.java:152)
	at appeng.me.GridNode.validateGrid(GridNode.java:108)
	at appeng.me.GridConnection.destroy(GridConnection.java:174)
	at appeng.me.GridNode.destroy(GridNode.java:224)
	at com.mordenkainen.equivalentenergistics.integration.ae2.grid.AEProxy.invalidate(AEProxy.java:159)
	at com.mordenkainen.equivalentenergistics.integration.ae2.grid.AEProxy.onChunkUnload(AEProxy.java:187)
	at com.mordenkainen.equivalentenergistics.integration.ae2.grid.IAEProxyHost.onChunkUnload(IAEProxyHost.java:35)
	at com.mordenkainen.equivalentenergistics.integration.ae2.tiles.TileAEBase.onChunkUnload(TileAEBase.java:38)
	at net.minecraft.world.World.func_72939_s(World.java:2515)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:673)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:986)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:842)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:692)
	at java.lang.Thread.run(Thread.java:750)

**Comment by serenibyss** [comment] 2024-12-23 19:08
Duplicate of #565

**Closed by serenibyss** 2024-12-23 19:08 UTC
